package com.l1vo.oslauncher
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.ArrowBack
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp
import java.util.Locale

@Composable fun L1voSettings(p:android.content.SharedPreferences,dark:Boolean,onTheme:(Boolean)->Unit,onFont:(String)->Unit,onBack:()->Unit,onWallpaper:()->Unit,onCube:(String)->Unit,onAccessibility:()->Unit,onDefaultLauncher:()->Unit){val ink=if(dark)Color(0xFFE9F0E9)else L1voInk;var anim by remember{mutableStateOf(p.getBoolean(ANIMATIONS,true))};var notif by remember{mutableStateOf(p.getBoolean(NOTIFICATIONS,true))};var pill by remember{mutableStateOf(p.getBoolean(PILL_APP,true))};var font by remember{mutableStateOf(p.getString(FONT,"Sans")?:"Sans")};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)){Row(verticalAlignment=Alignment.CenterVertically){IconButton(onClick=onBack){Icon(Icons.AutoMirrored.Outlined.ArrowBack,"Back",tint=ink)};Column(Modifier.weight(1f)){Text("L1vo",color=ink,style=MaterialTheme.typography.headlineMedium);Text("Settings",color=L1voGreen)};Icon(Icons.Outlined.Settings,"Settings",tint=L1voGreen)};Spacer(Modifier.height(18.dp));Group("Account",Icons.Outlined.Person,ink){Item("L1vo account",p.getString(ACCOUNT_NAME,"Guest") ?: "Guest",Icons.Outlined.Person,ink){};Toggle("Notifications",if(notif)"Enabled"else"Disabled",Icons.Outlined.Notifications,notif,{notif=it;p.edit().putBoolean(NOTIFICATIONS,it).apply()},ink)};Group("Appearance",Icons.Outlined.Palette,ink){Toggle("Dark theme",if(dark)"On"else"Off",Icons.Outlined.Palette,dark,onTheme,ink);Item("Wallpaper","Open Wallpaper Studio",Icons.Outlined.Wallpaper,ink,onWallpaper);Item("App font",font,Icons.Outlined.TextFields,ink){font=if(font=="Sans")"Serif"else if(font=="Serif")"Mono"else"Sans";onFont(font)}};Group("Home & Cube",Icons.Outlined.Tune,ink){Item("Settings slot","Customize upper-right cube section",Icons.Outlined.Settings,ink){onCube("settings")};Item("Gallery slot","Customize lower-left cube section",Icons.Outlined.Collections,ink){onCube("gallery")};Item("Calls slot","Customize lower-right cube section",Icons.Outlined.Call,ink){onCube("calls")}};Group("Accessibility",Icons.Outlined.Visibility,ink){Toggle("Animations",if(anim)"Enabled"else"Reduced",Icons.Outlined.Visibility,anim,{anim=it;p.edit().putBoolean(ANIMATIONS,it).apply()},ink);Toggle("Pill app",if(pill)"Enabled"else"Disabled",Icons.Outlined.Apps,pill,{pill=it;p.edit().putBoolean(PILL_APP,it).apply()},ink);Item("Android accessibility","Open system controls",Icons.Outlined.Visibility,ink,onAccessibility)};Group("Launcher",Icons.Outlined.Home,ink){Item("Default launcher","Choose L1vo as device home",Icons.Outlined.Home,ink,onDefaultLauncher)};Group("About",Icons.Outlined.Info,ink){Item("L1vo OS Launcher","Version 0.1.0",Icons.Outlined.Info,ink){}}}}
@Composable private fun Group(t:String,i:ImageVector,ink:Color,content:@Composable ColumnScope.()->Unit){Column{Row(verticalAlignment=Alignment.CenterVertically){Icon(i,t,tint=L1voGreen,modifier=Modifier.size(20.dp));Spacer(Modifier.width(8.dp));Text(t.uppercase(Locale.getDefault()),color=L1voGreen,fontWeight=androidx.compose.ui.text.font.FontWeight.Bold)};Card(colors=CardDefaults.cardColors(L1voPanel.copy(alpha=.95f)),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth().padding(vertical=8.dp)){Column(content=content)}}}
@Composable private fun Item(t:String,s:String,i:ImageVector,ink:Color,onClick:()->Unit){Surface(onClick=onClick,color=Color.Transparent,modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(i,t,tint=L1voDeepGreen);Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(t,color=ink);Text(s,color=ink.copy(alpha=.6f),style=MaterialTheme.typography.bodySmall)}}}}
@Composable private fun Toggle(t:String,s:String,i:ImageVector,checked:Boolean,onChange:(Boolean)->Unit,ink:Color){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(i,t,tint=L1voDeepGreen);Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(t,color=ink);Text(s,color=ink.copy(alpha=.6f),style=MaterialTheme.typography.bodySmall)};Switch(checked=checked,onCheckedChange=onChange)}}
