package com.l1vo.oslauncher
import android.content.Intent
import android.graphics.Bitmap
import androidx.compose.ui.graphics.Color
val L1voGreen=Color(0xFF3E6B34);val L1voDeepGreen=Color(0xFF315A2A);val L1voInk=Color(0xFF18241F);val L1voPanel=Color(0xFFF4F4E9);val L1voDark=Color(0xFF101612)
const val PREFS="l1vo_launcher";const val WALLPAPER="wallpaper";const val WALLPAPER_PLAYLIST="wallpaper_playlist";const val WALLPAPER_ALL="wallpaper_all";const val WALLPAPER_PLAYLIST_ALL="wallpaper_playlist_all";const val WALLPAPER_INTERVAL="wallpaper_interval";const val WALLPAPER_INTERVAL_ALL="wallpaper_interval_all";const val WALLPAPER_INTERVAL_MAIN="wallpaper_interval_main";const val WALLPAPER_INTERVAL_HOME="wallpaper_interval_home";const val WALLPAPER_INTERVAL_HUB="wallpaper_interval_hub";const val WALLPAPER_MODE="wallpaper_mode";const val WALLPAPER_MAIN="wallpaper_main";const val WALLPAPER_HOME="wallpaper_home";const val WALLPAPER_HUB="wallpaper_hub";const val WALLPAPER_PLAYLIST_MAIN="wallpaper_playlist_main";const val WALLPAPER_PLAYLIST_HOME="wallpaper_playlist_home";const val WALLPAPER_PLAYLIST_HUB="wallpaper_playlist_hub";const val WALLPAPER_MODE_MAIN="wallpaper_mode_main";const val WALLPAPER_MODE_HOME="wallpaper_mode_home";const val WALLPAPER_MODE_HUB="wallpaper_mode_hub";const val FONT_SIZE="font_size";const val FONT_COLOR="font_color";const val HIGHLIGHT_SHAPE="highlight_shape";const val HIGHLIGHT_SIZE="highlight_size";const val APPHUB_NAV="apphub_nav";const val APP_SIZE="app_size";const val APPHUB_COLUMNS="apphub_columns";const val APPHUB_HSPACE="apphub_hspace";const val APPHUB_VSPACE="apphub_vspace";const val LEAU_PACKAGE="com.liv.ol1viapa";const val ANIMATIONS="animations";const val DARK_THEME="dark_theme";const val FONT="font";const val NOTIFICATIONS="notifications";const val PILL_APP="pill_app";const val ACCOUNT_NAME="account_name"
data class LaunchableApp(val label:String,val packageName:String,val intent:Intent,val icon:Bitmap)
data class QuickSlot(val id:String,val label:String,val packageName:String?,val kind:SlotKind)
enum class SlotKind{HOME,SETTINGS,GALLERY,CALLS,APP}
