package com.l1vo.oslauncher
import android.content.Intent
import android.provider.Settings
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.ArrowBack
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

@Composable fun AppHub(apps:List<LaunchableApp>,ink:Color,onBack:()->Unit,onLeau:()->Unit,onWallpaper:()->Unit,onOpen:(LaunchableApp)->Unit,onL1vo:()->Unit){val context=LocalContext.current;LazyVerticalGrid(columns=GridCells.Fixed(4),modifier=Modifier.fillMaxSize(),contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){item(span={GridItemSpan(maxLineSpan)}){Row(verticalAlignment=Alignment.CenterVertically,modifier=Modifier.fillMaxWidth()){IconButton(onClick=onBack){Icon(Icons.AutoMirrored.Outlined.ArrowBack,"Back",tint=ink)};Column(Modifier.weight(1f)){Text("APP HUB",color=ink,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Light);Text("L1vo application space",color=L1voGreen)};IconButton(onClick=onWallpaper){Icon(Icons.Outlined.Wallpaper,"Wallpaper",tint=L1voGreen)}}};item(span={GridItemSpan(maxLineSpan)}){Title("L1vo","Native L1vo services",ink)};item(span={GridItemSpan(maxLineSpan)}){Surface(onClick=onL1vo,color=L1voPanel.copy(alpha=.95f),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Outlined.Eco,"L1vo",tint=L1voDeepGreen);Spacer(Modifier.width(14.dp));Column(Modifier.weight(1f)){Text("L1vo apps & features",color=ink,fontWeight=FontWeight.Medium);Text("Settings, Leau, Gallery and Phone",color=ink.copy(alpha=.6f),style=MaterialTheme.typography.bodySmall)};Icon(Icons.Outlined.ChevronRight,"Open",tint=L1voGreen)}}};item(span={GridItemSpan(maxLineSpan)}){Title("System","Core device controls",ink)};item(span={GridItemSpan(maxLineSpan)}){Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){SystemCard("Settings",Icons.Outlined.Settings){launch(context,Intent(Settings.ACTION_SETTINGS))};SystemCard("Phone",Icons.Outlined.Call){launch(context,Intent(Intent.ACTION_DIAL))};SystemCard("Gallery",Icons.Outlined.Collections){launch(context,Intent(Intent.ACTION_VIEW).apply{type="image/*"})}}};item(span={GridItemSpan(maxLineSpan)}){Title("Apps / All Apps","Every launchable app on this device",ink)};items(apps,key={it.packageName}){AppIcon(it,onOpen,ink)};item(span={GridItemSpan(maxLineSpan)}){Surface(onClick=onLeau,modifier=Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),color=L1voInk){Text("Open Leau",color=Color.White,modifier=Modifier.padding(16.dp),fontWeight=FontWeight.Medium)}}}}
@Composable private fun Title(t:String,s:String,ink:Color){Column(Modifier.fillMaxWidth()){Text(t.uppercase(),color=L1voGreen,fontWeight=FontWeight.Bold);Text(s,color=ink.copy(alpha=.6f),style=MaterialTheme.typography.bodySmall)}}
@Composable private fun RowScope.SystemCard(t:String,i:ImageVector,onClick:()->Unit){Surface(onClick=onClick,shape=RoundedCornerShape(18.dp),color=Color.White.copy(alpha=.82f),modifier=Modifier.weight(1f).height(80.dp)){Column(Modifier.fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Icon(i,t,tint=L1voDeepGreen);Text(t,style=MaterialTheme.typography.labelSmall)}}}
@Composable private fun AppIcon(a:LaunchableApp,onOpen:(LaunchableApp)->Unit,ink:Color){Column(horizontalAlignment=Alignment.CenterHorizontally){Surface(onClick={onOpen(a)},shape=RoundedCornerShape(16.dp),color=Color.White,modifier=Modifier.size(58.dp)){Image(a.icon.asImageBitmap(),a.label,Modifier.padding(8.dp),contentScale=ContentScale.Fit)};Text(a.label,color=ink,style=MaterialTheme.typography.labelSmall,maxLines=1)}}
@Composable fun L1voHub(ink:Color,onBack:()->Unit,onSettings:()->Unit,onLeau:()->Unit,onWallpaper:()->Unit){val context=LocalContext.current;Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)){Row(verticalAlignment=Alignment.CenterVertically){IconButton(onClick=onBack){Icon(Icons.AutoMirrored.Outlined.ArrowBack,"Back",tint=ink)};Column(Modifier.weight(1f)){Text("L1vo",style=MaterialTheme.typography.headlineMedium,color=ink);Text("L1vo apps & features",color=L1voGreen)};IconButton(onClick=onWallpaper){Icon(Icons.Outlined.Wallpaper,"Wallpaper",tint=L1voGreen)}};Spacer(Modifier.height(18.dp));Feature("L1vo Settings","Native launcher settings",Icons.Outlined.Settings,ink,onSettings);Feature("Leau","L1vo assistant",Icons.Outlined.Eco,ink,onLeau);Feature("L1vo Gallery","Media space",Icons.Outlined.Collections,ink){launch(context,Intent(Intent.ACTION_VIEW).apply{type="image/*"})};Feature("L1vo Phone & Contacts","Calls and contacts",Icons.Outlined.Call,ink){launch(context,Intent(Intent.ACTION_DIAL))}}}
@Composable private fun Feature(t:String,s:String,i:ImageVector,ink:Color,onClick:()->Unit){Surface(onClick=onClick,color=L1voPanel.copy(alpha=.95f),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth().padding(bottom=12.dp)){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Icon(i,t,tint=L1voDeepGreen,modifier=Modifier.size(28.dp));Spacer(Modifier.width(15.dp));Column{Text(t,color=ink,fontWeight=FontWeight.Medium);Text(s,color=ink.copy(alpha=.6f),style=MaterialTheme.typography.bodySmall)}}}}
